version: '3'
services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - npm_cache:/root/.npm
    tmpfs:
      - /app/dist
    environment:
      - DEBUG
      - PROFILE_BUILD
  travis:
    image: andredumas/travis-ci-cli
    volumes:
      - .:/repo:cached
      - ~/.travis:/travis
volumes:
  npm_cache:
